services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - data:/home/node/app
      - data:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@11.7.0 --activate && pnpm install && pnpm dev"
    depends_on:
      - mongo
      # - postgres
    env_file:
      - .env

volumes:
  data:
